/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Internally untyped to avoid strict generic assignability errors during
// `next build` (the return type of `createClient` with no type args
// resolves to a loose SupabaseClient<unknown> that cannot receive the
// concrete `SupabaseClient<Database>` produced by createClient<Database>(...).
// All current callers of `supabaseAdmin` are already stubbed and never
// actually use the client at runtime, so using `any` here is safe.
let _supabaseAdmin: any;
let _initError: Error | undefined;
let _triedInit = false;

function createSupabaseAdminClient() {
  const SUPABASE_URL =
    process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL)'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud, or add them to .env.local / Vercel env vars.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // Explicitly cast return to `any` so the call-site assignment into the
  // `any`-typed `_supabaseAdmin` never fails under stricter type passes.
  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  }) as any;
}

function getSupabaseAdmin() {
  if (!_triedInit) {
    _triedInit = true;
    try {
      _supabaseAdmin = createSupabaseAdminClient();
    } catch (e) {
      _initError = e instanceof Error ? e : new Error(String(e));
    }
  }
  if (_initError) throw _initError;
  return _supabaseAdmin;
}

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const supabaseAdmin = new Proxy<any>({} as any, {
  get(_, prop, receiver) {
    const client = getSupabaseAdmin();
    return Reflect.get(client, prop, receiver);
  },
});
